"""Oil-supply-shock impulse response, US illustration, regenerated by the pipeline.

Inputs: vendored files under data/vendor/ (kilian_var_data.csv, ff12_industry_returns.zip,
industrial_production.csv, the FRED INDPRO snapshot).
Outputs: results/.../supply_shock_irf.json and the pgfplots coordinates in
paper/_gen/fig_irf_data.tex, consumed by the fig:irf figure.
Purpose: estimate the Kilian (2009) recursive structural oil-supply shock, then Jorda (2005)
local projections of cumulative US industrial-production growth on the shock at horizons 0 to 24,
conditioning on a composition-stable equity trend, with HAC errors and a moving-block bootstrap
band. Sign convention: a positive coefficient means more oil supply raises production.
"""
from __future__ import annotations

import io  # noqa: F401
import json
import re
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.api as sm

from common.paths import DATA_ROOT, PAPER_GENERATED, FULL_SAMPLE_RESULTS

VENDOR = DATA_ROOT / "vendor"
OUT_JSON = FULL_SAMPLE_RESULTS / "supply_shock_irf.json"
OUT_TEX = PAPER_GENERATED / "fig_irf_data.tex"
HORIZONS = list(range(0, 25))
OWN_LAGS = 6
N_BOOT = 1000
SEED = 20240921


def structural_supply_shock(n_lags: int = 24) -> pd.Series:
    """Kilian recursive SVAR structural oil-supply shock from vendored VAR inputs."""
    from statsmodels.tsa.api import VAR

    df = pd.read_csv(VENDOR / "kilian_var_data.csv")
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    v = df.set_index("date")[["dprod", "rea", "rpoil"]].replace([np.inf, -np.inf], np.nan).dropna()
    res = VAR(v).fit(n_lags)
    U = res.resid
    P = np.linalg.cholesky(np.cov(U.values.T))
    struct = U.values @ np.linalg.inv(P).T
    s = pd.Series(struct[:, 0], index=U.index, name="supply_shock")
    s.index = s.index.to_period("M").to_timestamp()
    return s


def fixed_weight_equity() -> pd.Series:
    """Composition-stable equal-weight index across the 12 Fama-French industries."""
    path = VENDOR / "ff12_industry_returns.zip"
    txt = zipfile.ZipFile(path).read(zipfile.ZipFile(path).namelist()[0]).decode("latin-1")
    lines = txt.splitlines()
    start = next(i for i, l in enumerate(lines) if "Average Value Weighted Returns -- Monthly" in l)
    hdr = next(i for i in range(start + 1, len(lines)) if lines[i].lstrip().startswith(","))
    cols = [c.strip() for c in lines[hdr].split(",")]
    dates, rows = [], []
    for line in lines[hdr + 1:]:
        if not re.match(r"^\s*\d{6},", line):
            break
        cells = [c.strip() for c in line.split(",")]
        dates.append(pd.Timestamp(int(cells[0][:4]), int(cells[0][4:6]), 1))
        rows.append([pd.to_numeric(x, errors="coerce") for x in cells[1:]])
    R = pd.DataFrame(rows, index=pd.DatetimeIndex(dates), columns=cols[1:]).replace(
        [-99.99, -999.0], np.nan
    ) / 100.0
    ew = R.mean(axis=1)
    return (100 * (1 + ew.fillna(0)).cumprod()).rename("equity_fw")


def industrial_production() -> pd.Series:
    """FRED industrial production (INDPRO) from the vendored snapshot."""
    df = pd.read_csv(VENDOR / "industrial_production.csv")
    return pd.Series(
        pd.to_numeric(df.iloc[:, 1], errors="coerce").values,
        index=pd.to_datetime(df.iloc[:, 0], errors="coerce"),
    ).dropna().sort_index()


def _design(dep, shock, dlip, eq):
    cols = {"dep": dep, "shock": shock}
    for k in range(1, OWN_LAGS + 1):
        cols[f"dlip_{k}"] = dlip.shift(k)
    if eq is not None:
        cols["eq"] = eq
        for k in range(1, OWN_LAGS + 1):
            cols[f"eq_{k}"] = eq.shift(k)
    return pd.concat(cols, axis=1).replace([np.inf, -np.inf], np.nan).dropna()


def _lp_at_h(lip, shock, dlip, eq, h):
    dep = (lip.shift(-h) - lip.shift(1)).rename("dep") * 100.0
    d = _design(dep, shock, dlip, eq)
    X = sm.add_constant(d.drop(columns="dep"))
    m = sm.OLS(d["dep"], X).fit(cov_type="HAC", cov_kwds={"maxlags": h + OWN_LAGS})
    return float(m.params["shock"]), float(m.pvalues["shock"]), int(m.nobs), d


def _block_boot_ci(d, h, rng):
    y = d["dep"].to_numpy()
    X = sm.add_constant(d.drop(columns="dep")).to_numpy()
    jcol = list(sm.add_constant(d.drop(columns="dep")).columns).index("shock")
    n, bl = len(y), h + OWN_LAGS + 1
    nb = int(np.ceil(n / bl))
    betas = np.empty(N_BOOT)
    for b in range(N_BOOT):
        starts = rng.integers(0, n - bl + 1, size=nb)
        idx = np.concatenate([np.arange(s, s + bl) for s in starts])[:n]
        Xb, yb = X[idx], y[idx]
        try:
            betas[b] = np.linalg.lstsq(Xb, yb, rcond=None)[0][jcol]
        except np.linalg.LinAlgError:
            betas[b] = np.nan
    a = betas[np.isfinite(betas)]
    return float(np.percentile(a, 2.5)), float(np.percentile(a, 97.5))


def compute() -> list[dict]:
    shock = structural_supply_shock(24)
    lip = np.log(industrial_production()).rename("lip")
    lip.index = lip.index.to_period("M").to_timestamp()
    dlip = lip.diff().rename("dlip")
    eq = np.log(fixed_weight_equity()).diff().rename("eq")
    eq.index = eq.index.to_period("M").to_timestamp()
    rng = np.random.default_rng(SEED)
    rows = []
    for h in HORIZONS:
        b0, _, _, _ = _lp_at_h(lip, shock, dlip, None, h)
        b1, p1, n1, d1 = _lp_at_h(lip, shock, dlip, eq, h)
        lo, hi = _block_boot_ci(d1, h, rng)
        rows.append({"h": h, "beta_noeq": round(b0, 3), "beta_eq": round(b1, 3),
                     "hac_p": round(p1, 4), "ci_lo": round(lo, 3), "ci_hi": round(hi, 3), "n": n1})
    return rows


def _coords(rows, key):
    return " ".join(f"({r['h']},{r[key]})" for r in rows)


def main() -> int:
    rows = compute()
    peak = max(rows, key=lambda r: r["beta_eq"])
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps({"rows": rows, "peak": peak}))
    band = (" ".join(f"({r['h']},{r['ci_hi']})" for r in rows)
            + " " + " ".join(f"({r['h']},{r['ci_lo']})" for r in reversed(rows)))
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text(
        "% generated by src/analysis/supply_shock_irf.py — do not edit by hand\n"
        f"\\def\\irfConditioned{{{_coords(rows, 'beta_eq')}}}\n"
        f"\\def\\irfUnconditioned{{{_coords(rows, 'beta_noeq')}}}\n"
        f"\\def\\irfBand{{{band}}}\n"
    )
    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_TEX}")
    print(f"peak h={peak['h']} beta_eq={peak['beta_eq']:+.3f} ci=[{peak['ci_lo']:+.3f},{peak['ci_hi']:+.3f}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
